Support TYPO3 v12
martin-helmich/typo3-typoscript-lint pull request #131
Opened 2022-08-28 20:04 UTC by linawolf

resolves #129, #130

2022-09-16 11:19 UTC, oliverklee approved these changes

2022-09-16 11:24 UTC, oliverklee requested changes

2022-09-16 11:24 UTC, oliverklee commented on composer.json
> +        "php": "^7.4|^8.0|^8.1",
This is not necessary as `^8.0` already includes 8.1:
https://getcomposer.org/doc/articles/versions.md#caret-version-range-

2022-09-18 15:35 UTC, martin-helmich requested changes
Thanks for the contribution. In addition to @oliverklee's suggestions (thanks for the review! :+1:), I'd prefer having unit tests enabled for the new Symfony dependencies.

I've also noticed that the typecheck build jobs are failing, which appears to be an issue unrelated to this change. I'll investigate.

2022-09-18 15:35 UTC, martin-helmich commented on composer.json
> +        "symfony/event-dispatcher": "~3.0|~4.0|~5.0|^6.1",
Can we also add tests against the new Symfony versions? They're defined in the [`php` workflow file](https://github.com/martin-helmich/typo3-typoscript-lint/blob/master/.github/workflows/php.yml).

2022-10-16 12:53 UTC, closed without merging