feat: update symfony dependencies
martin-helmich/typo3-typoscript-lint pull request #176
Opened 2024-01-26 10:53 UTC by maikschneider

Tested with newer version of symfony packages: works like a charm!

2024-01-26 12:05 UTC, maikschneider commented on composer.json
> +		"symfony/event-dispatcher": "^4.4 || ^5.4 || ^6.2 || ^7.0",
Good point, thanks. I adjusted the version constraint.

2024-01-26 12:20 UTC, oliverklee approved these changes

2024-01-26 17:58 UTC, martin-helmich requested changes
Thanks! :+1:  Could you also add Symfony 7 to the build matrix (`.github/workflows/php.yml`, so that this project is also tested against the v7 versions?

2024-01-27 19:48 UTC, maikschneider commented
Yes, v7 is now added. I replaced the `6.2` and `6.3` with `6.4` as well.

2024-01-27 19:54 UTC, oliverklee approved these changes

2024-01-27 20:53 UTC, martin-helmich approved these changes
LGTM! 👍

2024-01-27 21:09 UTC, oliverklee approved these changes

2024-01-28 10:26 UTC, martin-helmich approved these changes
So, this looks good in general :+1:  -- 867a2bfa4307d9a9ab3644f8f3a3a6f1d425ee06 was a good catch, I didn't remember we had that workaround in there. Only reason the tests are still failing is because the upstream library `helmich/typo3-typoscript-parser` is not yet compatible with the symfony v7 libraries; I'll see if we can bump these as well...

2024-02-26 10:34 UTC, maikschneider commented
Waiting for https://github.com/martin-helmich/typo3-typoscript-parser/pull/95 to be merged

2024-02-26 20:34 UTC, merged